spring:
  datasource:
    url: jdbc:h2:file:~/testH2
    driverClassName: org.h2.Driver
    username: admin
    password: nimda

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

nasa:
  url: https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos
  apiKey: ${NASA_API_KEY}

